version: "3.11"

volumes:
  jaeger_temp:

services:
  jaeger:
    container_name: jaeger
    image: docker.io/jaegertracing/all-in-one:1.39.0
    volumes:
      - jaeger_temp:/tmp
    ports:
      - "16686:16686/tcp" # webui is listening
      - "14268:14268/tcp" # accepting spans in compact jaeger thrift format over http
      - "6831:6831/udp" # accepting spans in compact jaeger thrift format over udp
