package math

// Sequence generates array of given size with elements generated by seed function provided
func Sequence[T Number](size int, seed func(int) T) (seq []T) {
	seq = make([]T, size)
	for i := 0; i < size; i++ {
		seq[i] = seed(i)
	}
	return seq
}
